{{- range $index, $service := .Values.services}}
{{- if $service.variables }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $service.app.name }}-{{ $service.app.type }}-{{ $service.app.brand }}-vars
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
data:
  {{- range $key, $value := $service.variables }}
  {{ $key }}: {{ $value | quote -}}
  {{ end }}
---
{{- end }}
{{- end }}