{{- range $index, $job := .Values.jobs}}
{{- if $job.variables }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $job.name }}-cron-job-{{ $job.brand }}-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
stringData:
  {{- range $key, $value := $job.secrets }}
  {{ $key }}: {{ $value | quote -}}
  {{- end }}
---
{{- end }}
{{- end }}