{{- range $index, $job := .Values.jobs}}
{{- if $job.variables }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $job.name }}-cron-job-{{ $job.brand }}-vars
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
data:
  {{- range $key, $value := $job.variables }}
  {{ $key }}: {{ $value | quote -}}
  {{ end }}
---
{{- end }}
{{- end }}