{{- range $index, $service := .Values.services}}
{{- range $index, $ingress := $service.ingress}}
{{- if $ingress.middleware }}
{{- range $index, $middleware := $ingress.middleware}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
{{- range $key, $rulename := $middleware.rule}}
  name: {{ $ingress.host }}-{{ lower $key }}-{{ regexReplaceAll "/" (lower ($ingress.pathPrefix | default "")) "" | default $index }}
spec:
  {{- with $middleware.rule }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}