{{- range $index, $service := .Values.services}}
{{- if $service.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $service.app.name }}-{{ $service.app.type }}-{{ $service.app.brand }}-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
stringData:
  {{- range $key, $value := $service.secrets }}
  {{ $key }}: {{ $value | quote -}}
  {{- end }}
---
{{- end }}
{{- end }}